# Generated by Django 4.1 on 2022-08-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagemail', models.CharField(max_length=9999)),
                ('firstdatemail', models.DateTimeField()),
                ('seconddatemail', models.DateTimeField()),
                ('tagmail', models.IntegerField()),
            ],
        ),
    ]
