# Generated by Django 4.1 on 2022-08-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='messagemail',
            field=models.TextField(),
        ),
    ]
