# Generated by Django 4.1 on 2022-08-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_clients_alter_mailing_tagmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('status', models.TextField()),
                ('idmailing', models.IntegerField()),
                ('idclient', models.IntegerField()),
            ],
        ),
    ]
